spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false